[package]
name = "presto_spatial_join_blog"
version = "0.1.0"
authors = ["James A. Gill <jagill@fb.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
csv = "1.1"
serde_json = "1.0"
flate2 = "1.0"
geojson= "0.18"
anyhow = "1.0"
rstar = "0.7"
encoding = "0.2"
